package com.dapp.backend.enums;

public enum NewsCategory {
    HEALTH_GENERAL,
    VACCINE_INFO,
    DISEASE_PREVENTION,
    NUTRITION,
    CHILDREN_HEALTH,
    WOMEN_HEALTH,
    ELDERLY_CARE,
    MEDICAL_RESEARCH,
    HEALTH_TIPS,
    COVID_19,
    SEASONAL_DISEASES,
    VACCINATION_SCHEDULE
}
